/**
 * Wave 14 — Invoice Agent (pure draft preview).
 *
 * Takes a quote's status + data and returns what an invoice WOULD
 * look like if created right now. NEVER calls the database. NEVER
 * writes anything. The actual insert happens via the
 * `create_invoice_from_quote(uuid)` Postgres RPC, called from the
 * server action `createInvoiceFromQuote` — this function only
 * produces the preview the `InvoiceDraftCard` renders.
 *
 * Mirror of the RPC's preconditions so the UI never offers a button
 * the database would reject:
 *   • quote.status === 'completed'
 *   • quote total > 0
 *   • quote has at least one line item
 *
 * If any precondition fails, `reason !== "ready"` and `blockers`
 * carries the human-readable explanations.
 */
import type { QuoteData, QuoteStatus } from "@/lib/quote-types";
import type { InvoiceDraftPreview } from "@/lib/types/invoice";
import { round2 } from "@/lib/quote-defaults";

/** Due date is 7 days out from "now"; the RPC sets the authoritative one. */
function defaultDueIso(): string {
  return new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
}

export function runInvoiceAgent(
  status: QuoteStatus,
  quoteData: QuoteData | null,
): InvoiceDraftPreview {
  const dueDateIso = defaultDueIso();
  const blockers: string[] = [];

  if (!quoteData) {
    return {
      invoiceNumberPreview: "INV-—",
      subtotal: 0,
      taxAmount: 0,
      totalAmount: 0,
      currency: "NZD",
      dueDateIso,
      clientName: null,
      lineItemCount: 0,
      reason: "quote-missing-data",
      blockers: ["Quote has no data — finish the quote before invoicing."],
    };
  }

  if (status !== "completed") {
    blockers.push(
      `Mark the job complete before invoicing (current stage: ${status}).`,
    );
  }

  const subtotal = round2(Number(quoteData.subtotal_before_tax) || 0);
  const taxAmount = round2(Number(quoteData.tax_amount) || 0);
  const totalAmount = round2(Number(quoteData.total) || 0);
  const currency = quoteData.currency || "NZD";
  const clientName = quoteData.client?.name?.trim() || null;
  const lineItemCount = Array.isArray(quoteData.line_items)
    ? quoteData.line_items.length
    : 0;

  if (lineItemCount === 0) {
    blockers.push("Quote has no line items — nothing to charge for.");
  }
  if (totalAmount <= 0) {
    blockers.push("Quote total is 0 — set prices on the line items.");
  }

  const reason: InvoiceDraftPreview["reason"] =
    status !== "completed"
      ? "quote-not-completed"
      : blockers.length > 0
        ? "quote-missing-data"
        : "ready";

  return {
    // Preview only — the real number is `INV-<8 hex>` generated by the RPC.
    invoiceNumberPreview: "INV-…",
    subtotal,
    taxAmount,
    totalAmount,
    currency,
    dueDateIso,
    clientName,
    lineItemCount,
    reason,
    blockers,
  };
}
